# -*- coding: utf-8 -*-
"""ProductReview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zxe-l9tZcs-tXEurEI6wgw_jQa0s9XgJ
"""

!pip install spacy nltk scikit-learn seaborn matplotlib
!python -m spacy download en_core_web_sm

import pandas as pd
import numpy as np
import json
import re
import spacy
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

nltk.download('stopwords')

from google.colab import files
uploaded = files.upload()

reviews = []

with open("Cell_Phones_and_Accessories_5.json") as f:
    for line in f:
        reviews.append(json.loads(line))

df = pd.DataFrame(reviews)

df = df[['reviewText', 'overall']]
df.dropna(inplace=True)

print("Total Reviews:", len(df))
df.head()

def label_sentiment(rating):
    if rating >= 4:
        return "Positive"
    else:
        return "Negative"

df['sentiment'] = df['overall'].apply(label_sentiment)
df['sentiment'].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.countplot(x=df['sentiment'])
plt.title("Distribution of Sentiment Classes")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.show()

pip install wordcloud

# -------- FAST PREPROCESSING --------

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# Stopwords
stop_words = set(stopwords.words('english'))

# Keep negations
negations = {"not", "no", "never"}
stop_words = stop_words - negations


def clean_text(text):
    # Lowercase
    text = text.lower()

    # Remove HTML
    text = re.sub(r'<.*?>', '', text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Keep only letters
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenize (simple split)
    words = text.split()

    # Remove stopwords + Lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)


# Apply
df['clean_text'] = df['reviewText'].astype(str).apply(clean_text)

df.head()

from wordcloud import WordCloud

text = " ".join(df['clean_text'])

wordcloud = WordCloud(width=800, height=400).generate(text)

plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.title("Word Cloud of Reviews")
plt.show()

# -------- SMALL POS TAGGING SECTION (FAST & CLEAN) --------

import spacy
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns

# Load lightweight spaCy (disable heavy components)
nlp_pos = spacy.load("en_core_web_sm", disable=["parser", "ner"])

# Take small sample (reduce to 500 if needed)
sample_df = df.sample(n=1000, random_state=42)

feature_list = []

# Use nlp.pipe for batch processing (much faster than apply)
for doc in nlp_pos.pipe(sample_df['reviewText'].astype(str), batch_size=200):
    for token in doc:
        if token.pos_ == "NOUN":
            feature_list.append(token.lemma_.lower())

# Count top features
feature_counts = Counter(feature_list)
top_features = feature_counts.most_common(10)

print("Top 10 Most Discussed Features:\n")
for feature, count in top_features:
    print(feature, ":", count)

# Plot
features = [x[0] for x in top_features]
counts = [x[1] for x in top_features]

plt.figure(figsize=(8,5))
sns.barplot(x=counts, y=features)
plt.title("Top 10 Most Discussed Features")
plt.xlabel("Frequency")
plt.ylabel("Feature")
plt.show()

# -------- FAST DEPENDENCY PARSING --------

import spacy
from collections import Counter

# Load full model (parser needed here)
nlp_dep = spacy.load("en_core_web_sm")

# Use small subset ONLY
dep_sample = df.sample(n=800, random_state=42)

feature_sentiment = []

for doc in nlp_dep.pipe(dep_sample['reviewText'].astype(str), batch_size=100):
    for token in doc:

        # Case 1: Adjective modifier (e.g., weak battery)
        if token.dep_ == "amod" and token.head.pos_ == "NOUN":
            feature_sentiment.append((token.head.lemma_.lower(), token.lemma_.lower()))

        # Case 2: Subject complement (battery is weak)
        if token.dep_ == "acomp" and token.head.dep_ == "ROOT":
            for child in token.head.children:
                if child.dep_ == "nsubj" and child.pos_ == "NOUN":
                    feature_sentiment.append((child.lemma_.lower(), token.lemma_.lower()))

print("Sample Feature → Adjective pairs:\n")
print(feature_sentiment[:20])

from spacy import displacy

sentence1 = "The battery is weak but the screen is beautiful."
sentence2 = "The charger stopped working after a week and became very hot."

doc1 = nlp_dep(sentence1)
doc2 = nlp_dep(sentence2)

displacy.render(doc1, style='dep', jupyter=True)
displacy.render(doc2, style='dep', jupyter=True)

# -------- FAST NEGATIVE FEATURE EXTRACTION --------

negative_sample = df[df['sentiment'] == "Negative"].sample(n=600, random_state=42)

neg_pairs = []

for doc in nlp_dep.pipe(negative_sample['reviewText'].astype(str), batch_size=100):
    for token in doc:
        if token.dep_ == "amod" and token.head.pos_ == "NOUN":
            neg_pairs.append((token.head.lemma_.lower(), token.lemma_.lower()))

top_negative = Counter(neg_pairs).most_common(10)

print("Top Negative Feature Pairs:\n")
print(top_negative)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=15000,        # more vocabulary
    ngram_range=(1,2),         # unigrams + bigrams
    min_df=3,                  # ignore rare noise
    max_df=0.9,                # remove overly common words
    sublinear_tf=True          # log scaling improves performance
)

X = tfidf.fit_transform(df['clean_text'])
y = df['sentiment']

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df["clean_text"])
y = df["sentiment"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.svm import LinearSVC

model = LinearSVC(class_weight='balanced')
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, pos_label="Positive"))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

feature_names = vectorizer.get_feature_names_out()
coefficients = model.coef_[0]

top_positive = coefficients.argsort()[-10:][::-1]
top_negative = coefficients.argsort()[:10]

positive_words = [feature_names[i] for i in top_positive]
negative_words = [feature_names[i] for i in top_negative]

plt.figure()
plt.barh(positive_words, coefficients[top_positive])
plt.title("Top Words Indicating Positive Sentiment")
plt.show()

plt.figure()
plt.barh(negative_words, coefficients[top_negative])
plt.title("Top Words Indicating Negative Sentiment")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=["Negative","Positive"],
            yticklabels=["Negative","Positive"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

def predict_review(review):

    cleaned = clean_text(review)

    vector = vectorizer.transform([cleaned])   # only transform

    prediction = model.predict(vector)[0]

    return prediction

review = "The battery drains very fast and the charger stopped working."

result = predict_review(review)

print("Review:", review)
print("Prediction:", result)